name: Update Version on PR to Main

on:
  pull_request:
    branches:
      - main

jobs:
  update_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git user
        run: |
          git config --local user.email "jashtilekov888@gmail.com"
          git config --local user.name "Eldiyar888"

      - name: Update version
        run: npm version patch

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Bump version [skip ci]"
          git push origin main
