name: Update Version on PR to Main

on:
  pull_request:
    branches:
      - main

jobs:
  update_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update version
        run: npm version patch
